name: Qodana Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.2
        with:
          project-dir: .
          results-dir: ./qodana-results

      - name: Upload Qodana Results
        uses: actions/upload-artifact@v3
        with:
          name: qodana-results
          path: ./qodana-results
